---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
    
  - name: create ansible_admin user
    tags: always
    user:
      name: ansible_admin
      groups: root
  
  - name: add ssh key for ansible_admin
    tags: always
    authorized_key:
      user: ansible_admin
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICs3a12H0ALwzVu64hOrzboPZl4cL63L6m6GeN4PIaoE ansible"
  
  - name: add sudoers file for ansible_admin
    tags: always
    copy:
      src: sudoer_ansible_admin
      dest: /etc/sudoers.d/ansible_admin
      owner: root
      group: root
      mode: 0440

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers